library(robotstxt)
library(rvest)
library(stringr)
library(dplyr)
laptop="https://www.flipkart.com/search?q=laptop+for+women+under+2000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.price_range.from%3D20000&p%5B%5D=facets.price_range.to%3D40000"
path=paths_allowed(laptop)
filpkart=read_html(laptop)
View(filpkart)
brand<- filpkart %>% html_nodes(".KzDlHZ") %>% html_text()
View(brand)
price<- filpkart %>% html_nodes("._4b5DiR") %>% html_text()
View(price)
storage<- filpkart %>% html_nodes(".J\\+igdf:nth-child(2)") %>% html_text()
View(storage)
inch<- filpkart %>% html_nodes(".J\\+igdf:nth-child(2)") %>% html_text()
View(inch)
os<- filpkart %>% html_nodes(".J\\+igdf:nth-child(3)")%>% html_text()
View(os)
laps=data.frame(brand,price,storage,inch,os)
View(laps)
website=write.csv(laps,"website.csv")
View(website)
